### ISSUE TITLE
Previews don't work, peek RuntimeError

### ISSUE THREAD

**Issue by uwidev** [ndtoan96/ouch.yazi#14]
Yazi version: 0.3.3 (Arch Linux 2024-09-05)
Plugin commit version: db1488358941a2bc9918fa91c304d6724a0bb608

When I hover over a `.zip`, I get the following log.
```
  2024-12-02T00:39:01.627007Z ERROR yazi_plugin::isolate::peek: RuntimeError("[string \"ouch\"]:39: attempt to call a nil value (field 'Text')\nstack traceback:\n\t[string \"ouch\"]:39: in function <[string \"ouch\"]:3>")
    at yazi-plugin/src/isolate/peek.rs:50
```

Here are my yaml config contents. It's very barebones.
```toml
# keymap.toml
[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"
```

```toml
# yazi.toml
[manager]
sort_by = "modified"
sort_reverse = true


[plugin]
prepend_previewers = [
	# Markdown glow
	{ name = "*.md", run = "glow" },

	# Archive previewer
	{ mime = "application/*zip", run = "ouch" },
	{ mime = "application/x-tar", run = "ouch" },
	{ mime = "application/x-bzip2", run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar", run = "ouch" },
	{ mime = "application/x-xz", run = "ouch" },
]

prepend_preloaders = []


[opener]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
```
